import './globals.css'
import Provider from './provider'
import Header from '@/components/custom/Header'
import ConvexClientProvider from './ConvexClientProvider'
import { Toaster } from '@/components/ui/sonner'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <ConvexClientProvider>
          <Provider>
            <Header />
            {children}
            <Toaster/>
          </Provider>
        </ConvexClientProvider>
      </body>
    </html>
  )
}
